exclude: 'docs|node_modules|migrations|.git|.tox'
default_stages: [commit]
fail_fast: true

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml

  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort

  - repo: https://github.com/pycqa/flake8.git
    rev: 3.8.4
    hooks:
    - id: flake8
      exclude: 'tests|env|docs,api/test1.py'
      args: ['--config=setup.cfg','--ignore=F401,F841,W503, E501, E203','--max-line-length=120']
      additional_dependencies: [flake8-isort]
